version: "3.9"
services:
  postgress:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes
    volumes:
      - db-data:/var/lib/postgresql/data/
  # pgAdmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - postgress
  #   ports:
  #     - "82:80"
  #   environment:
  #     - 'PGADMIN_DEFAULT_EMAIL=admin@mail.ru'
  #     - 'PGADMIN_DEFAULT_PASSWORD=root'
  notes:
    container_name: NotesApi
    build:
      context: Microservices/Notes
      dockerfile: Dockerfile
    depends_on:
      - postgress
    ports:
      - "5222:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  db-data: